--------------------------------------------------------
--  파일이 생성됨 - 수요일-1월-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AS_PRODUCT
--------------------------------------------------------

  CREATE TABLE "HR"."AS_PRODUCT" 
   (	"AS_PRODUCTID" NUMBER, 
	"AS_PRODUCTNAME" VARCHAR2(20 BYTE), 
	"AS_PRODUCTPRICE" NUMBER, 
	"AS_PRODUCTDATE" DATE, 
	"AS_PRODUCTCOUNT" NUMBER, 
	"AS_LOCALNUM" NUMBER, 
	"AS_CATEGORY" NUMBER, 
	"AS_DEPARTURE" VARCHAR2(20 BYTE), 
	"AS_ARIDATE" DATE, 
	"AS_DEPDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ASCATEGORY
--------------------------------------------------------

  CREATE TABLE "HR"."ASCATEGORY" 
   (	"AS_CATEGORY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ASLOCAL
--------------------------------------------------------

  CREATE TABLE "HR"."ASLOCAL" 
   (	"AS_LOCALNUM" NUMBER, 
	"AS_LOCALCOUNT" VARCHAR2(20 BYTE), 
	"AS_LOCALCITY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ASMEMBER
--------------------------------------------------------

  CREATE TABLE "HR"."ASMEMBER" 
   (	"AS_ID" VARCHAR2(20 BYTE), 
	"AS_PW" VARCHAR2(20 BYTE), 
	"AS_NAME" VARCHAR2(20 BYTE), 
	"AS_EMAIL" VARCHAR2(20 BYTE), 
	"AS_BIRTH" DATE, 
	"AS_SEX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ASPAYMANET
--------------------------------------------------------

  CREATE TABLE "HR"."ASPAYMANET" 
   (	"PAY_CARDONW" VARCHAR2(20 BYTE), 
	"PAY_CARDNUM" NUMBER, 
	"AS_PRODUCTID" NUMBER, 
	"PAY_EXPIREDATE" DATE, 
	"PAY_PASSPORT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table AS_PRODUCT
--------------------------------------------------------

  ALTER TABLE "HR"."AS_PRODUCT" MODIFY ("AS_DEPDATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."AS_PRODUCT" MODIFY ("AS_ARIDATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."AS_PRODUCT" MODIFY ("AS_DEPARTURE" NOT NULL ENABLE);
  ALTER TABLE "HR"."AS_PRODUCT" MODIFY ("AS_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "HR"."AS_PRODUCT" MODIFY ("AS_LOCALNUM" NOT NULL ENABLE);
  ALTER TABLE "HR"."AS_PRODUCT" MODIFY ("AS_PRODUCTDATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."AS_PRODUCT" MODIFY ("AS_PRODUCTPRICE" NOT NULL ENABLE);
  ALTER TABLE "HR"."AS_PRODUCT" MODIFY ("AS_PRODUCTNAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."AS_PRODUCT" MODIFY ("AS_PRODUCTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASCATEGORY
--------------------------------------------------------

  ALTER TABLE "HR"."ASCATEGORY" MODIFY ("AS_CATEGORY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASLOCAL
--------------------------------------------------------

  ALTER TABLE "HR"."ASLOCAL" MODIFY ("AS_LOCALCITY" NOT NULL ENABLE);
  ALTER TABLE "HR"."ASLOCAL" MODIFY ("AS_LOCALCOUNT" NOT NULL ENABLE);
  ALTER TABLE "HR"."ASLOCAL" MODIFY ("AS_LOCALNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASMEMBER
--------------------------------------------------------

  ALTER TABLE "HR"."ASMEMBER" MODIFY ("AS_SEX" NOT NULL ENABLE);
  ALTER TABLE "HR"."ASMEMBER" MODIFY ("AS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASPAYMANET
--------------------------------------------------------

  ALTER TABLE "HR"."ASPAYMANET" MODIFY ("PAY_EXPIREDATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."ASPAYMANET" MODIFY ("AS_PRODUCTID" NOT NULL ENABLE);
  ALTER TABLE "HR"."ASPAYMANET" MODIFY ("PAY_CARDNUM" NOT NULL ENABLE);
  ALTER TABLE "HR"."ASPAYMANET" MODIFY ("PAY_CARDONW" NOT NULL ENABLE);
